//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Categories = new HashSet<Category>();
            this.Mappings = new HashSet<Mapping>();
        }
    
        public long ApplicationId { get; set; }
        public long SuiteId { get; set; }
        public string ApplicationName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Suite Suite { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Mapping> Mappings { get; set; }
    }
}
