//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditArea
    {
        public AuditArea()
        {
            this.Audits = new HashSet<Audit>();
        }
    
        public int AuditAreaId { get; set; }
        public string AuditAreaName { get; set; }
    
        public virtual ICollection<Audit> Audits { get; set; }
    }
}
