//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvironmentType
    {
        public EnvironmentType()
        {
            this.Environments = new HashSet<Environment>();
        }
    
        public int EnvironmentTypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Environment> Environments { get; set; }
    }
}
