//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public long MappingId { get; set; }
        public long SuiteId { get; set; }
        public long EnvironmentId { get; set; }
        public long ApplicationId { get; set; }
        public long RegionId { get; set; }
        public long ServerId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public long ParameterId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Parameter Parameter { get; set; }
        public virtual Region Region { get; set; }
        public virtual Server Server { get; set; }
        public virtual Suite Suite { get; set; }
    }
}
