//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SuiteUsers = new HashSet<SuiteUser>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual ICollection<SuiteUser> SuiteUsers { get; set; }
    }
}
