//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long CategoryId { get; set; }
        public long ApplicationId { get; set; }
        public string CategoryName { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
