//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public string OptionName { get; set; }
        public string OptionValue { get; set; }
        public bool AutoLoad { get; set; }
        public bool IsEncrypted { get; set; }
        public bool IsActive { get; set; }
    }
}
