//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfDB.Engine.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public Server()
        {
            this.Mappings = new HashSet<Mapping>();
        }
    
        public long ServerId { get; set; }
        public long SuiteId { get; set; }
        public string ServerName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Mapping> Mappings { get; set; }
        public virtual Suite Suite { get; set; }
    }
}
